---
title: "Nitrogen project (1)"
author: "Patty Park"
date: "4/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

```

```{r}
#importing data into R
nitrogen_soil <- read_csv("nitrogen_soil.csv")
north_parcel <- read_csv("np_pc.csv")
north_parcel
nitrogen_soil2 <- rename(nitrogen_soil, 'nonnative' = 'Total Nonnative PC')
nitrogen_soil2
nitrogen_soil3 <- read_csv("Nitrogen_soil (2).csv")
nitrogen_soil3 <- rename(nitrogen_soil3, 'nonnative'='Total Nonnative PC')
nitrogen_soil3

```



```{r}
#creating nitrate graph
nitrate_graph <- ggplot(nitrogen_soil2, aes(x=Nitrate, y=nonnative, )) +geom_point() +geom_smooth(method=lm , color="red", se=TRUE) + theme_classic()
nitrate_graph

#make column graph? x axis is zone, y axis is nitrogen concentration (nitrate and ammonium)

#+facet_wrap(~zone) this is for regression

#start google slides (intro, methods,etc, conclusion)

```

```{r}
#creating ammonium graph
ammonium_graph <- ggplot(nitrogen_soil2, aes(x=Ammonium, y=nonnative)) +geom_point() +geom_smooth(method=lm , color="red", se=FALSE)
ammonium_graph
```

```{r}
#Nitrate graph with separate zones
nitrate_graph2 <- ggplot(nitrogen_soil3, aes(x=Nitrate, y=nonnative)) +geom_point() +geom_smooth(method=lm , color="red", se=TRUE) + theme_classic() + facet_wrap(~Zone)
nitrate_graph2

```

``` {r}
#ammonium graph with separate zones
ammonium_graph2 <- ggplot(nitrogen_soil3, aes(x=Ammonium, y=nonnative)) +geom_point() +geom_smooth(method=lm , color="red", se=TRUE) + theme_classic() + facet_wrap(~Zone)
ammonium_graph2

```

```{r}
plot(x=nitrogen_soil2$Nitrate, y=nitrogen_soil2$nonnative, ,xlab="Nitrate concentration", yxlab="Total Nonnative PC", main="Nitrate and Nonnative PC")

```